{
 "title": "Cowrie",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "COWRIE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://opengraph.githubassets.com/9f4a7f9511756b888439bf0104073111c52309994a82dc4c7597f1e874447c8b/cowrie/cowrie\" alt=\"Mi imagen\" width=\"400\">\n\n\n"
   }
  },
  {
   "title": "Descargas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id)\nFROM cowrie.downloads\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Ips Únicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct ip)\nFROM cowrie.sessions\nWHERE\n  $__timeFilter(starttime)\n"
    }
   ]
  },
  {
   "title": "Clientes SSH recibidos",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "select version from cowrie.clients;\r\n"
    }
   ]
  },
  {
   "title": "Clientes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id)\nFROM cowrie.clients\n"
    }
   ]
  },
  {
   "title": "Intentos de Auth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM cowrie.auth\n\n"
    }
   ]
  },
  {
   "title": "Procedencia de los Ataques SSH",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "select latitude, longitude from cowrie.coord;"
    }
   ]
  },
  {
   "title": "Inputs más usados",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "select input, count(*) from cowrie.input group by input;"
    }
   ]
  },
  {
   "title": "Usuarios más Usados",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "SELECT\r\n  username,\r\n  count(*) AS attempt_count\r\nFROM cowrie.auth\r\nGROUP BY username\r\nORDER BY attempt_count DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Contraseñas más Usadas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "SELECT\r\n  password,\r\n  count(*) AS attempt_count\r\nFROM cowrie.auth\r\nGROUP BY password\r\nORDER BY attempt_count DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Número de Conexiones Autenticadas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  id\nFROM cowrie.auth\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  { "title": "HONEY WEB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 35 },
   "options": {
    "content": "<img src=\"https://www.penacerrada-urizaharra.eus/wp-content/uploads/2020/09/ico-farmacia.png\" alt=\"farmaciapaafin\" width=\"400\">\n\n\n"
   }
  },
  {
   "title": "User-Agents más utilizados",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 35 },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "select SO, count(*) as cantidad from laravel.sospechosos group by SO order by cantidad desc;"
    }
   ]
  },
  {
   "title": "IPs Únicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ncount(distinct ip)\nFROM laravel.sospechosos;"
    }
   ]
  },
  {
   "title": "Cantidas de cada Tipo de Ataque",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "select motivo, count(*) from laravel.sospechosos group by motivo;"
    }
   ]
  },
  {
   "title": "User-Agents más utilizados",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "select navegador, count(*) as cantidad from laravel.sospechosos group by navegador order by cantidad desc;"
    }
   ]
  },
  {
   "title": "Rutas Usadas",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "select url, count(*) from laravel.honeypot_urls_accessed group by url;"
    }
   ]
  },
  {
   "title": "Procedencia de los Ataques",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 51 },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "SELECT\r\n  latitud AS lat,\r\n  longitud AS lon,\r\n  COUNT(*) AS value\r\nFROM laravel.sospechosos\r\nGROUP BY lat, lon;\r\n"
    }
   ]
  },
  {
   "title": "OPENCANARY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 68 },
     "options": {
      "content": "<img src=\"https://docs.cyderes.cloud/img/thinkst2.png\" alt=\"farmaciapaafin\" width=\"400\">\n\n\n"
     }
    },
    {
     "title": "Puertos Utilizados",
     "type": "stat",
     "gridPos": { "h": 8, "w": 9, "x": 3, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "dataset": "cowrie",
       "rawSql": "select distinct src_port from opencanary.open_ftp;"
      }
     ]
    },
    {
     "title": "Procedencia de los ataques FTP",
     "type": "geomap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "dataset": "cowrie",
       "rawSql": "select latitud, longitud from opencanary.map_ftp;"
      }
     ]
    },
    {
     "title": "Usuarios Utilizados",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "cowrie",
       "rawSql": "select distinct user_name from opencanary.open_ftp;"
      }
     ]
    },
    {
     "title": "Contraseñas Utilizados",
     "type": "stat",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "dataset": "cowrie",
       "rawSql": "select distinct password from opencanary.open_ftp;"
      }
     ]
    },
    {
     "title": "Cantidad de intentos por IP",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "dataset": "cowrie",
       "rawSql": "select src_ip, count(*) from opencanary.open_ftp GROUP BY src_ip;"
      }
     ]
    }
   ]
  },
  {
   "title": "VPN/PROXY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 69 },
     "options": {
      "content": "<img src=\"https://play-lh.googleusercontent.com/U2xXb93iF7PBbNU-pxvqYvK1cP9jchBH3Gz0scGwExO9DcO5wPZGUD2sTNtT_C8eGfg\" alt=\"farmaciapaafin\" width=\"400\">\n\n\n"
     }
    },
    {
     "title": "Procedencia de las IPs Obtenidas",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 5, "x": 3, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "cowrie",
       "rawSql": "SELECT 'IPs Reales' AS ip, COUNT(*) AS cantidad\r\nFROM proveedor_ip.clean_ips\r\n\r\nUNION\r\n\r\nSELECT tipo, COUNT(*) AS cantidad\r\nFROM proveedor_ip.ips\r\nGROUP BY tipo;\r\n"
      }
     ]
    },
    {
     "title": "Proveedores Más Utilizados",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 8, "y": 69 },
     "targets": [
      {
       "dataset": "cowrie",
       "rawSql": "SELECT proveedor, tipo, COUNT(*) AS cantidad\r\nFROM proveedor_ip.ips\r\nGROUP BY proveedor, tipo\r\nORDER BY cantidad DESC;\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "FAKEFTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attemps per IP",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 584 },
     "targets": [
      {
       "dataset": "cowrie",
       "rawSql": "SELECT ip, ptr, COUNT(*) AS repeticiones\r\nFROM ftp.attem\r\nGROUP BY ip, ptr\r\nORDER BY repeticiones DESC;"
      }
     ]
    },
    {
     "title": "Used Passwords",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 584 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT password, attemps AS repeticiones\r\nFROM ftp.password\r\nORDER BY repeticiones DESC;\r\n"
      }
     ]
    }
   ]
  }
 ]
}